"""GENERATED by `<binary> describe-interface` — do not edit.

The bundled form of the worker's interface, refreshed automatically when a
local cargo build disagrees with it. Inside a task container (no cargo
build available) this is what declares the task.
"""

DESCRIPTOR = {'flyte_interface_version': 1, 'task': 'flaky', 'inputs': [{'name': 'seed', 'type': 'integer', 'required': True}], 'outputs': [{'name': 'o0', 'type': 'string'}]}
