//! The in-pod worker entrypoint: honors the Python SDK's container arg/env
//! contract (`flyte/_bin/runtime.py`), loads `inputs.pb`, runs the task fn with
//! trace support, and uploads `outputs.pb` or `error.pb`. Always exits 0 —
//! task failure travels via `error.pb`, matching the Python runtime.

use std::future::Future;
use std::pin::Pin;
use std::process::ExitCode;

use prost::Message as _;

use crate::context::{self, RuntimeState};
use crate::controller::{runtime, Controller};
use crate::error::Error;
use crate::interface::TaskInterface;
use crate::idl::{
    container_error, execution_error, ContainerError, ErrorDocument, Inputs, Outputs,
    RunIdentifier,
};
use crate::storage::Storage;

/// Boxed future returned by a task entry fn.
pub type TaskFuture = Pin<Box<dyn Future<Output = Result<Outputs, Error>> + Send>>;

/// A task entrypoint generated by `#[flyte::task]`.
pub struct TaskEntry {
    pub name: &'static str,
    /// The task's interface, derived from the fn signature. A fn pointer rather
    /// than a value because `LiteralType` is a proto message and cannot be
    /// constructed in a const.
    pub interface: fn() -> TaskInterface,
    pub run: fn(Inputs) -> TaskFuture,
}

/// Run a future on the SDK runtime with no backend attached: every
/// `#[flyte::trace]` fn simply executes its body. The dev-loop entrypoint —
/// call it from a test, or anywhere you want the task to run in-process.
pub fn run<F: Future>(fut: F) -> F::Output {
    runtime().block_on(fut)
}

#[derive(Default, Debug)]
struct WorkerConfig {
    inputs_uri: Option<String>,
    output_path: Option<String>,
    run_base_dir: Option<String>,
    action_name: Option<String>,
    run_name: Option<String>,
    project: Option<String>,
    domain: Option<String>,
    org: Option<String>,
}

/// `{{.actionName}}`-style values mean the backend did not substitute the
/// template — fall back to env (mirrors runtime.py).
fn real_value(v: String) -> Option<String> {
    if v.starts_with("{{") || v.is_empty() {
        None
    } else {
        Some(v)
    }
}

fn parse_args(args: impl Iterator<Item = String>) -> WorkerConfig {
    let mut cfg = WorkerConfig::default();
    let mut args = args.peekable();
    while let Some(arg) = args.next() {
        let mut take_value = || args.next().and_then(real_value);
        match arg.as_str() {
            "--inputs" | "-i" => cfg.inputs_uri = take_value(),
            "--outputs-path" | "-o" => cfg.output_path = take_value(),
            "--run-base-dir" => cfg.run_base_dir = take_value(),
            "--name" => cfg.action_name = take_value(),
            "--run-name" => cfg.run_name = take_value(),
            "--project" => cfg.project = take_value(),
            "--domain" => cfg.domain = take_value(),
            "--org" => cfg.org = take_value(),
            // Known flags we accept but don't use in v0.
            "--version" | "--raw-data-path" | "--checkpoint-path" | "--prev-checkpoint"
            | "--run-start-time" | "--image-cache" | "--tgz" | "--pkl" | "--dest"
            | "--interface" => {
                let _ = args.next();
            }
            // Resolver args are a Python-ism; everything after is theirs.
            "--resolver" => break,
            // Subcommand tokens ("a0") and anything unrecognized: skip.
            _ => {}
        }
    }
    cfg
}

fn env_nonempty(key: &str) -> Option<String> {
    std::env::var(key).ok().filter(|v| !v.is_empty())
}

fn truthy(v: &str) -> bool {
    matches!(v.to_lowercase().as_str(), "1" | "true" | "t" | "yes")
}

struct ResolvedConfig {
    inputs_uri: Option<String>,
    output_path: String,
    run_base_dir: String,
    action_name: String,
    run_id: RunIdentifier,
}

fn resolve_config(cfg: WorkerConfig) -> Result<ResolvedConfig, Error> {
    let require = |value: Option<String>, flag: &str, env: &str| {
        value.ok_or_else(|| {
            Error::System(format!(
                "missing required configuration: pass {flag} or set {env}"
            ))
        })
    };
    let action_name = require(
        cfg.action_name.or_else(|| env_nonempty("ACTION_NAME")),
        "--name",
        "ACTION_NAME",
    )?;
    let run_name = require(
        cfg.run_name.or_else(|| env_nonempty("RUN_NAME")),
        "--run-name",
        "RUN_NAME",
    )?;
    let project = require(
        cfg.project
            .or_else(|| env_nonempty("FLYTE_INTERNAL_EXECUTION_PROJECT")),
        "--project",
        "FLYTE_INTERNAL_EXECUTION_PROJECT",
    )?;
    let domain = require(
        cfg.domain
            .or_else(|| env_nonempty("FLYTE_INTERNAL_EXECUTION_DOMAIN")),
        "--domain",
        "FLYTE_INTERNAL_EXECUTION_DOMAIN",
    )?;
    let org = cfg.org.or_else(|| env_nonempty("_U_ORG_NAME")).unwrap_or_default();
    let run_base_dir = require(
        cfg.run_base_dir.or_else(|| env_nonempty("_U_RUN_BASE")),
        "--run-base-dir",
        "_U_RUN_BASE",
    )?;
    let output_path = cfg
        .output_path
        .unwrap_or_else(|| Storage::join(&run_base_dir, &action_name));
    Ok(ResolvedConfig {
        inputs_uri: cfg.inputs_uri,
        output_path,
        run_base_dir,
        action_name,
        run_id: RunIdentifier {
            org,
            project,
            domain,
            name: run_name,
        },
    })
}

fn build_controller(run_id: RunIdentifier) -> Result<Controller, Error> {
    if env_nonempty("_UNION_EAGER_API_KEY").is_some() {
        return Controller::with_auth(run_id, 10);
    }
    let raw = env_nonempty("_U_EP_OVERRIDE").unwrap_or_else(|| "host.docker.internal:8090".into());
    let endpoint = if raw.starts_with("http://") || raw.starts_with("https://") {
        raw
    } else {
        let insecure = env_nonempty("_U_INSECURE").is_some_and(|v| truthy(&v))
            || raw.contains("localhost")
            || raw.contains("127.0.0.1")
            || raw.contains("docker");
        format!("{}{raw}", if insecure { "http://" } else { "https://" })
    };
    Controller::without_auth(run_id, endpoint, 10)
}

fn error_document(err: &Error) -> ErrorDocument {
    let (code, origin) = match err {
        Error::User { code, .. } => (code.clone(), execution_error::ErrorKind::User),
        // A rejected or timed-out condition is a user outcome, not a system
        // fault: reporting it as a system error would give it the wrong retry
        // semantics and disagree with the Python SDK's codes.
        Error::Condition { outcome, .. } => {
            (outcome.code().to_string(), execution_error::ErrorKind::User)
        }
        _ => ("SystemError".to_string(), execution_error::ErrorKind::System),
    };
    ErrorDocument {
        error: Some(ContainerError {
            code,
            message: err.to_string(),
            kind: container_error::Kind::Recoverable as i32,
            origin: origin as i32,
        }),
    }
}

async fn execute(entry: &TaskEntry, state: &RuntimeState, inputs_uri: Option<&str>) {
    // Prewarm the informer so its watch stream has the whole startup window to
    // sync trace actions recorded by a previous attempt (cold-cache replay).
    let _ = state
        .controller
        .lookup_action("__prewarm__", &state.action_name)
        .await;
    if state.is_retry {
        // Retry attempt: previously recorded traces arrive over the freshly
        // opened watch stream; give it a beat before the first replay lookup.
        let wait_ms = env_nonempty("_F_TRACE_SYNC_WAIT_MS")
            .and_then(|v| v.parse().ok())
            .unwrap_or(1000u64);
        tokio::time::sleep(std::time::Duration::from_millis(wait_ms)).await;
    }

    let result: Result<Outputs, Error> = async {
        let inputs = match inputs_uri {
            Some(uri) => {
                let data = state.storage.get(uri).await?;
                Inputs::decode(data.as_ref())?
            }
            None => Inputs::default(),
        };
        (entry.run)(inputs).await
    }
    .await;

    match result {
        Ok(outputs) => {
            let uri = Storage::join(&state.output_path, "outputs.pb");
            let data = bytes::Bytes::from(outputs.encode_to_vec());
            match state.storage.put(&uri, data).await {
                Ok(()) => tracing::info!(task = entry.name, "task succeeded, outputs uploaded"),
                Err(e) => tracing::error!(task = entry.name, "outputs upload failed: {e}"),
            }
        }
        Err(err) => {
            tracing::error!(task = entry.name, "task failed: {err}");
            let uri = Storage::join(&state.output_path, "error.pb");
            let data = bytes::Bytes::from(error_document(&err).encode_to_vec());
            if let Err(e) = state.storage.put(&uri, data).await {
                tracing::error!(task = entry.name, "error upload failed: {e}");
            }
        }
    }

    state.controller.finalize(&state.action_name).await;
}

/// The worker process entrypoint: call from `main` with the entry generated by
/// `#[flyte::task]`.
pub fn worker_main(entry: TaskEntry) -> ExitCode {
    // Answered before anything else touches env, the controller, or logging, so
    // `docker run --rm <image> describe-interface` works with no setup at all.
    //
    // Safe to key off argv[1]: the backend's first token is always an action
    // name (`a0`, or a base36 hash) and can never be a hyphenated literal.
    if std::env::args().nth(1).as_deref() == Some("describe-interface") {
        println!("{}", (entry.interface)().to_json(entry.name));
        return ExitCode::SUCCESS;
    }

    let _ = tracing_subscriber::fmt()
        .with_env_filter(
            tracing_subscriber::EnvFilter::try_from_default_env()
                .unwrap_or_else(|_| tracing_subscriber::EnvFilter::new("info")),
        )
        .try_init();

    // The legacy QueueService+StateService path is gone: always use the unified
    // ActionsService. Set before the controller (or any thread) starts.
    std::env::set_var("_U_USE_ACTIONS", "1");
    if env_nonempty("_UNION_EAGER_API_KEY").is_none() {
        if let Some(key) = env_nonempty("EAGER_API_KEY") {
            std::env::set_var("_UNION_EAGER_API_KEY", key);
        }
    }
    if let Some(key) = env_nonempty("_UNION_EAGER_API_KEY") {
        // API keys from `flyte create api-key` are url-safe base64; the
        // controller decodes with the standard alphabet. Translating -_ to +/
        // yields the same bytes, so both encodings work.
        std::env::set_var("_UNION_EAGER_API_KEY", key.replace('-', "+").replace('_', "/"));
    }
    if env_nonempty("_F_TRACE_COMPLETION_TIMEOUT").is_none() {
        std::env::set_var("_F_TRACE_COMPLETION_TIMEOUT", "5");
    }

    let cfg = match resolve_config(parse_args(std::env::args().skip(1))) {
        Ok(cfg) => cfg,
        Err(e) => {
            eprintln!("flyte worker configuration error: {e}");
            return ExitCode::FAILURE;
        }
    };

    // Controller construction blocks on the shared runtime internally — it must
    // happen here on the plain main thread, before we enter that runtime.
    let controller = match build_controller(cfg.run_id.clone()) {
        Ok(c) => c,
        Err(e) => {
            eprintln!("flyte worker controller init failed: {e}");
            return ExitCode::FAILURE;
        }
    };

    // FLYTE_ATTEMPT_NUMBER is 0-based; >0 means a previous attempt may have
    // recorded traces worth replaying.
    let is_retry = env_nonempty("FLYTE_ATTEMPT_NUMBER")
        .and_then(|v| v.parse::<u32>().ok())
        .unwrap_or(0)
        > 0;

    let state = context::install(RuntimeState::new(
        controller,
        Storage::new(),
        cfg.action_name,
        cfg.run_base_dir,
        cfg.output_path,
        is_retry,
    ));

    runtime().block_on(async {
        tokio::select! {
            _ = execute(&entry, &state, cfg.inputs_uri.as_deref()) => {}
            res = state.controller.watch_for_errors() => {
                if let Err(e) = res {
                    tracing::error!("controller background failure: {e}");
                    let uri = Storage::join(&state.output_path, "error.pb");
                    let doc = error_document(&Error::System(e.to_string()));
                    let _ = state.storage.put(&uri, bytes::Bytes::from(doc.encode_to_vec())).await;
                }
            }
        }
    });

    // Task failure is reported via error.pb; the container itself exits 0.
    ExitCode::SUCCESS
}
