# Autogenerated from `<binary> describe-interface` — safe to delete, any
# launch with a built binary writes it back. Committed so a container, which
# has no cargo, still has an interface to declare the task from.
DESCRIPTOR = {'flyte_interface_version': 1, 'task': 'fanout', 'inputs': [{'name': 'n', 'type': 'integer', 'required': True}], 'outputs': [{'name': 'o0', 'type': 'string'}]}
