use proc_macro::TokenStream;
use quote::quote;
use syn::spanned::Spanned;

use crate::trace::{result_ok_type, typed_params};

pub fn expand(attr: TokenStream, item: TokenStream) -> TokenStream {
    let func = syn::parse_macro_input!(item as syn::ItemFn);
    match expand_inner(attr, func) {
        Ok(tokens) => tokens.into(),
        Err(e) => e.to_compile_error().into(),
    }
}

fn expand_inner(attr: TokenStream, func: syn::ItemFn) -> syn::Result<proc_macro2::TokenStream> {
    if !attr.is_empty() {
        return Err(syn::Error::new(
            proc_macro2::Span::call_site(),
            "#[flyte::task] takes no arguments",
        ));
    }
    if func.sig.asyncness.is_none() {
        return Err(syn::Error::new(
            func.sig.fn_token.span(),
            "#[flyte::task] requires an async fn",
        ));
    }

    let (ok_ty, is_unit) = result_ok_type(&func.sig)?;
    let params = typed_params(&func.sig)?;

    let vis = &func.vis;
    let fn_name = &func.sig.ident;
    let fn_name_str = fn_name.to_string();
    let entry_ident = syn::Ident::new(&format!("{fn_name}_entry"), fn_name.span());

    let decode_params = params.iter().map(|(ident, ty)| {
        let name = ident.to_string();
        quote! {
            let #ident = <#ty as ::flyte::FlyteType>::from_literal(
                ::flyte::types::input_literal(&__inputs, #name)?,
            )?;
        }
    });
    let arg_idents: Vec<_> = params.iter().map(|(ident, _)| ident).collect();

    let run_and_encode = if is_unit {
        quote! {
            #fn_name(#(#arg_idents),*).await?;
            ::core::result::Result::Ok(::flyte::types::build_outputs(::std::vec![]))
        }
    } else {
        quote! {
            let __value = #fn_name(#(#arg_idents),*).await?;
            ::core::result::Result::Ok(::flyte::types::build_outputs(::std::vec![
                ("o0", <#ok_ty as ::flyte::FlyteType>::to_literal(&__value)?),
            ]))
        }
    };

    Ok(quote! {
        #func

        /// Generated by `#[flyte::task]` — pass to `flyte::worker_main`.
        #vis fn #entry_ident() -> ::flyte::TaskEntry {
            ::flyte::TaskEntry {
                name: #fn_name_str,
                run: |__inputs: ::flyte::idl::Inputs| {
                    ::std::boxed::Box::pin(async move {
                        #(#decode_params)*
                        #run_and_encode
                    })
                },
            }
        }
    })
}
