"""GENERATED by `hello-trace describe-interface` — do not edit.

The bundled form of the worker's interface. On a dev machine `task.py`
reads the interface live from the built binary and refreshes this file when it
is stale; inside a task container (where there is no cargo build) this module is
what the code bundle carries.
"""

DESCRIPTOR = {'flyte_interface_version': 1, 'task': 'my_task', 'inputs': [{'name': 'x', 'type': 'integer', 'required': True}, {'name': 'label', 'type': 'string', 'required': True}], 'outputs': [{'name': 'o0', 'type': 'string'}]}
