"""Declare the Rust hello-trace worker as a Flyte task, and launch it.

No Python runs inside the task container, and there is nothing to configure:
the worker image is declared as `flyte.Image` layers (see rust_worker_image)
and built by Flyte's image builder on first run — no Dockerfile, no docker on
your machine, no registry push. Later runs reuse the built image.

The task's interface is **not written here** — it comes from the binary itself
(`describe-interface`), so renaming a Rust parameter can never silently diverge
from what the launcher sends. On a dev machine the interface is read live from
your cargo build and `interface_gen.py` is refreshed if stale; inside a task
container the generated module (carried by the code bundle) stands in.

Run it (--x / --label are derived from the interface):

    flyte run rust_task.py my_task --x 21 --label demo

Caveat: `flyte run` always uploads a small Python code bundle this container
never reads (the CLI has no --version flag and --copy-style none requires one).
Programmatic launches can skip it:
flyte.with_runcontext(version=..., copy_style="none").run(my_task, ...).

Prefer a small hand-optimized image? `scripts/build-image.sh` builds the
multi-stage one (~147MB vs ~1.5GB single-stage here); swap the task's image
for `flyte.Image.from_base("<pushed-uri>")` to use it.

Env (all optional):
    RUST_IMAGE_REGISTRY   push registry for the built image; omit to use the
                          remote builder's managed registry
"""

import inspect
import json
import os
import subprocess
from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path

import flyte
from flyte.extend import TaskTemplate
from flyte.models import NativeInterface, SerializationContext

import interface_gen

BINARY = "hello-trace"
_CRATE_DIR = Path(__file__).resolve().parent  # examples/hello-trace
_WORKSPACE = _CRATE_DIR.parents[1]  # flyte-sdk-rust
_RS_CONTROLLER = _WORKSPACE.parent / "flyte-sdk" / "rs_controller"

SUPPORTED_DESCRIPTOR_VERSION = 1

# The descriptor's closed set of type tags -> Python types. `struct` is msgpack on
# the wire (mashumaro-compatible), which round-trips as an untyped dict.
_PY_TYPES = {
    "integer": int,
    "float": float,
    "string": str,
    "boolean": bool,
    "struct": dict,
}


def _local_binary() -> Path | None:
    for profile in ("release", "debug"):
        candidate = _WORKSPACE / "target" / profile / BINARY
        if candidate.exists():
            return candidate
    return None


@lru_cache(maxsize=None)
def load_descriptor() -> dict:
    """The worker's interface, from the single source of truth: the binary.

    Dev machine (a cargo build exists): ask the binary, and refresh
    interface_gen.py when it is stale so the bundled copy tracks the source.
    Task container (no cargo build): use interface_gen.py — module-level code
    also runs inside the parent's container in the workflow path, where neither
    cargo nor docker exists.
    """
    binary = _local_binary()
    if binary is None:
        return interface_gen.DESCRIPTOR

    raw = subprocess.run(
        [str(binary), "describe-interface"], check=True, capture_output=True, text=True
    ).stdout
    desc = json.loads(raw)
    version = desc.get("flyte_interface_version")
    if version != SUPPORTED_DESCRIPTOR_VERSION:
        raise RuntimeError(
            f"worker speaks interface version {version}, this launcher supports "
            f"{SUPPORTED_DESCRIPTOR_VERSION} — update the SDK or rebuild"
        )

    if desc != interface_gen.DESCRIPTOR:
        _regenerate_interface_module(desc)
    return desc


def _regenerate_interface_module(desc: dict) -> None:
    header = (
        '"""GENERATED by `hello-trace describe-interface` — do not edit.\n'
        "\n"
        "The bundled form of the worker's interface. On a dev machine `rust_task.py`\n"
        "reads the interface live from the built binary and refreshes this file when it\n"
        "is stale; inside a task container (where there is no cargo build) this module is\n"
        "what the code bundle carries.\n"
        '"""\n'
    )
    body = "\nDESCRIPTOR = " + repr(desc) + "\n"
    try:
        (_CRATE_DIR / "interface_gen.py").write_text(header + body)
        print(f"refreshed interface_gen.py from {BINARY} describe-interface")
    except OSError:
        pass  # read-only checkout: the live descriptor is still what gets used


def _py_type(var: dict) -> type:
    try:
        return _PY_TYPES[var["type"]]
    except KeyError:
        raise RuntimeError(
            f"input/output {var['name']!r} has type {var['type']!r}, which cannot be "
            f"launched from Python yet"
            + (f" ({var['detail']})" if "detail" in var else "")
        ) from None


def native_interface(desc: dict) -> NativeInterface:
    """Build the Flyte interface from the descriptor.

    Required-ness is keyed off `inspect.Parameter.empty` — that is the sentinel
    `NativeInterface.required_inputs()` checks. Using None here instead would make
    every input optional-with-default-None, and the container would then die on a
    missing input rather than the CLI refusing up front.
    """
    for var in desc["inputs"]:
        if not var.get("required", True):
            raise RuntimeError(
                f"input {var['name']!r} declares a default, which needs a matching "
                f"literal the descriptor does not carry yet"
            )
    return NativeInterface.from_types(
        {v["name"]: (_py_type(v), inspect.Parameter.empty) for v in desc["inputs"]},
        {v["name"]: _py_type(v) for v in desc["outputs"]},
    )


def rust_worker_image() -> flyte.Image:
    """The worker image, declared as Flyte image layers.

    Declarative layers instead of a Dockerfile, so this works with the REMOTE
    image builder (`image: {builder: remote}` in config) — no local docker
    needed, and because no layer asks for Python, the built image contains no
    venv, just the Rust toolchain and the binary.

    Once the `flyte` crate is published to crates.io, the build context is JUST
    this crate's folder — cargo fetches the SDK like any dependency (see the
    post-publication shape below). Today the crate has path dependencies, so the
    workspace and rs_controller ride along in their expected relative layout.

    Known limits: single-stage (the DSL has no stages), so the toolchain and
    sources stay in the final image; no ENTRYPOINT layer exists in the image
    IDL, so container_args puts the binary path in args[0]; `Image.platform` is
    ignored by the remote builder (you get the buildkit pod's arch — amd64 in
    Union cloud).
    """
    image = (
        flyte.Image.from_base("rust:1-bookworm")
        .clone(name=f"{BINARY}-worker", registry=os.environ.get("RUST_IMAGE_REGISTRY"), extendable=True)
        # Replaces the SDK's default ignore set, which does NOT know about
        # cargo's target/ — without this the upload context is gigabytes.
        .with_dockerignore(_CRATE_DIR / ".dockerignore")
        # pyo3 build-time needs (temporary until the pure-Rust controller swap);
        # single-stage means libpython is present at runtime for free.
        .with_apt_packages("python3", "python3-dev", "pkg-config")
        .with_env_vars({"PYO3_PYTHON": "python3"})
        # The local docker builder chowns COPY layers to a `flyte` user; the
        # remote builder chowns to the base's runtime user (root here). Create
        # the user so the same definition builds under either.
        .with_commands(["useradd --system --create-home flyte || true"])
    )

    # -- Post-publication shape: context = just this crate. ----------------
    # return (
    #     image.with_source_folder(_CRATE_DIR, "./app")
    #     .with_commands([f"cd app && cargo build --release --bin {BINARY}"
    #                     f" && install target/release/{BINARY} /usr/local/bin/{BINARY}"])
    # )

    # -- Pre-publication shim: path deps (crate -> ../../crates/flyte -> -----
    #    ../../../flyte-sdk/rs_controller) need both trees, laid out as the
    #    Cargo.tomls expect. Delete when `flyte` is on crates.io.
    #
    #    Rust sources ONLY, never the whole workspace: the image tag is a hash
    #    of each copied folder's contents, and the workspace accumulates files
    #    that change on every run (.flyte/local-cache/cache.db is written by
    #    `flyte run` itself, Python imports drop __pycache__, interface_gen.py
    #    refreshes). Copying the workspace made every run mint a new tag and
    #    rebuild the image it was about to use.
    return (
        image.with_source_folder(_RS_CONTROLLER, "./flyte-sdk/rs_controller")
        .with_source_file(_WORKSPACE / "Cargo.toml", "./flyte-sdk-rust/Cargo.toml")
        .with_source_file(_WORKSPACE / "Cargo.lock", "./flyte-sdk-rust/Cargo.lock")
        .with_source_folder(_WORKSPACE / "crates", "./flyte-sdk-rust/crates")
        .with_source_file(_CRATE_DIR / "Cargo.toml", "./flyte-sdk-rust/examples/hello-trace/Cargo.toml")
        .with_source_folder(_CRATE_DIR / "src", "./flyte-sdk-rust/examples/hello-trace/src")
        .with_commands(
            [
                f"cd flyte-sdk-rust && cargo build --release -p {BINARY}"
                f" && install target/release/{BINARY} /usr/local/bin/{BINARY}"
            ]
        )
    )


@dataclass(kw_only=True)
class RustWorkerTask(TaskTemplate):
    """A plain-container task speaking the standard worker arg contract."""

    async def execute(self, *args, **kwargs):
        # Only reached under mode="local" / `flyte run --local`, which would need
        # us to run the container ourselves (see flyte.extras.ContainerTask).
        raise NotImplementedError("remote-only task; --local is not supported")

    def container_args(self, sctx: SerializationContext):
        # Mirrors flyte._task.AsyncFunctionTaskTemplate.container_args, trimmed to
        # what crates/flyte/src/worker.rs::parse_args consumes.
        #
        # - args[0] is the binary path: the built image has no ENTRYPOINT (the
        #   image IDL has no such layer) and the task's container command is
        #   empty, so k8s execs args directly. (Under an image whose ENTRYPOINT
        #   is the binary, this token is just an unrecognized arg the worker
        #   skips — one arg list, valid either way.)
        # - "a0" is the leading token the Python runtime also emits; the worker
        #   skips it (it is a click subcommand name there, meaningless here).
        # - input/output paths keep their {{.input}} / {{.outputPrefix}} defaults,
        #   which the backend substitutes per action. This is also what makes the
        #   task work as a CHILD action: the controller deliberately leaves those
        #   unset so the node executor fills them in.
        # - {{.runName}} / {{.actionName}} are NOT in the backend's substitution
        #   set. The worker receives them literally, discards any "{{...}}" value,
        #   and takes the names from the RUN_NAME / ACTION_NAME env the backend
        #   injects. Kept as forward-compatible placeholders.
        # - --run-base-dir is never an arg; it arrives only as _U_RUN_BASE.
        return [
            f"/usr/local/bin/{BINARY}",
            "a0",
            "--inputs",
            sctx.input_path,
            "--outputs-path",
            sctx.output_path,
            "--run-name",
            "{{.runName}}",
            "--name",
            "{{.actionName}}",
        ]


_descriptor = load_descriptor()

# The module attribute name is what `flyte run` uses as the subcommand, so this
# is named to match the Rust fn: CLI subcommand == task name == `my_task`.
my_task = RustWorkerTask(
    name=_descriptor["task"],
    # A dedicated type for clarity — nothing python runs in this container.
    # Safe: the leaseworker resolves unregistered types to the default pod
    # plugin (leaseworker/plugin/registry.go), the same handler "container"
    # gets. Avoid "raw-container": that one injects the copilot sidecar.
    task_type="rust-task",
    image=rust_worker_image(),
    interface=native_interface(_descriptor),
)

# Sets parent_env / parent_env_name, without which serialization fails. Bound to a
# module-level name so workflow.py can pass it as depends_on.
rust_env = flyte.TaskEnvironment.from_task("rust_env", my_task)
